### PR TITLE
Handle nil values returned by sb-unix:unix-fast-select

### PR DESCRIPTION
**Pull request by ak-coram**
On my system (FreeBSD 13.1-RELEASE) #1011 caused errors when `sb-unix:unix-fast-select` returned `nil` (I'm not sure why this would happen in the first place). This change ignores these values and resolves the issue for me, please let me know if there's a better solution.

Thanks!

### CODE REVIEW

**Comment by PuercoPop** [comment]
https://github.com/sbcl/sbcl/blob/master/src/code/unix.lisp#L86 You are right, the syscall will return nil and the the errno in the second value  when it is not successful

**Comment by PuercoPop** [comment]
I think the fix would be to check the errno returned by the syscall but I still have to test it. @jl2 any thoughts?
```patch
modified   ioloop.lisp
@@ -289,13 +289,13 @@ (defmethod io-loop ((info sbcl-io-loop) &key description)
                                     (floor remaining-ms 1000000))
                                   (values nil nil))))
                        ;; Actually block for events
-                       (let ((rval (multiple-value-call
-                                       #'sb-unix:unix-fast-select (1+ maxfd)
-                                     (sb-alien:addr rfds)
-                                     (sb-alien:addr wfds)
-                                     (sb-alien:addr efds)
-                                     (compute-timeout))))
-                         (cond ((= rval -1)
+                       (multiple-value-bind (rval errno)
+                           (sb-unix:unix-fast-select (1+ maxfd)
+                                                     (sb-alien:addr rfds)
+                                                     (sb-alien:addr wfds)
+                                                     (sb-alien:addr efds)
+                                                     (compute-timeout))
+                         (cond ((or errno (= rval -1))
                                 ;; ???
                                 (let ((errno rval))
                                   (cond ((eql errno sb-unix:eintr)
```

**Comment by jl2** [comment]
Yes, that looks good to me.

**Comment by ak-coram** [comment]
@PuercoPop, @jl2: Thanks! I'll test this and will update the PR.

**Comment by ak-coram** [comment]
Rebased this on current master

**Comment by Phundrak** [comment]
I tested your branch on my Linux machine, it indeed fixes the issue.

**Comment by ak-coram** [comment]
@Phundrak: thanks! @PuercoPop, @jl2 I've updated the PR to push these errors to the debug log instead (`*debug-level* >= 5`)

**Comment by PuercoPop** [comment]
@ak-coram Thanks for taking the initiative

**Pull request merged**
