### PR TITLE
Use CLX's Xinerama extesion to query screen heads

### PR DESCRIPTION
**Pull request by PuercoPop**
I've done some light testing with Xephyr, `Xephyr -screen 640x480 -screen 640x480 +xinerama :1 &`

### CODE REVIEW

**Comment by PuercoPop** [comment]
Michael Raskin noted that this PR did away with the case where xinerama wasn't present, I'll amend it

**Comment by PuercoPop** [comment]
There are still some cases to debug with checking for the presence of Xinerama

**Comment by jorams** [comment]
@PuercoPop What kind of cases are those? My testing suggests this works and can be merged.

**Comment by PuercoPop** [comment]
I don't have a multi-monitor setup so I used Xephyr for testing.

One problem is that it seems to detect xinerama as active even when it isn't. cc @38a938c2 

For example using the following Xephyr configuration
```
$ Xephyr -screen 640x480 -xinerama :1 &
```
The result of `(xlib/xinerama:xinerama-is-active *display*)` is true.

**Comment by jorams** [comment]
That is probably related to this [bug report](https://bugs.freedesktop.org/show_bug.cgi?id=11505). In short, the Xinerama extension can be disabled, but the protocol support is still implemented otherwise. The RandR extension, for example, implements the Xinerama protocol. ([This](https://bugs.freedesktop.org/show_bug.cgi?id=11118) bug report reports the same thing explicitly about Xephyr).

I'm not sure if it's even possible, these days, to run an X server that doesn't report Xinerama support.

**Comment by jorams** [comment]
Ok, I did some more testing. It *is* possible to disable Xinerama in Xephyr, by adding `-extension RANDR` to the line you posted above.

Then starting StumpWM results in the following exception:

```
debugger invoked on a XLIB::ABSENT-EXTENSION in thread
#<THREAD "main thread" RUNNING {10031C6753}>:
  Extension XINERAMA isn't defined for display #<XLIB:DISPLAY :1 (The X.Org Foundation R11903000)>

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [QUIT-STUMPWM] Quit Stumpwm

(XLIB::X-ERROR XLIB::ABSENT-EXTENSION :NAME :XINERAMA :DISPLAY #<XLIB:DISPLAY :1 (The X.Org Foundation R11903000)>)
   source: (APPLY #'ERROR CONDITION KEYARGS)
0] 
```

**Comment by jorams** [comment]
It's quite easy to fix: Just make sure `(xlib:query-extension *display* "XINERAMA")` doesn't return `NIL`, before calling `xinerama-is-active`.

**Comment by jorams** [comment]
This should now work correctly. Before merging, it's probably a good idea to remove the `xdpyinfo` mention from the README, because it's no longer necessary.

**Comment by jorams** [comment]
Alright, I think this is ready to merge.

**Pull request merged**
