### PR TITLE
Fix 994: Replace sb-unix:unix-select with sb-unix:unix-fast-select

### PR DESCRIPTION
**Pull request by jl2**
This fixes [Issue 994](https://github.com/stumpwm/stumpwm/issues/994), caused by SBCL [removing `#'sb-unix:unix-select`](https://github.com/sbcl/sbcl/commit/856a6ac26f2e7ac74d5f26cd4390bc1bd7e63c4e)

### CODE REVIEW

**Comment by jl2** [comment]
I checked [another PR build](https://github.com/stumpwm/stumpwm/runs/7702949228?check_suite_focus=true#step:3:5299), and it also gets this error, but since it's running interactively, the debugger comes up, and somehow the process exits normally and the error ends up ignored.

The problem appears to be line 81 of manual.lisp with UTF-8 characters:

`(ppcre:register-groups-bind (name) ("^€€€ (.*)" line)`

I don't get this error locally with SBCL 2.2.7, so it may be fixed by switching to a newer SBCL.

I think the best solution is to configure SBCL to use UTF-8 during the build, but I'm not sure how to configure that.  Another option is to replace "€€€" with something else, but that seems lame.

Any suggestions on how to move forward?  I'll have some time this evening to work on it.

**Comment by sandric** [comment]
Just wanted to leave mb helpful note that I had the same issue with sbcl error during make, and after running make on your pr branch - stumpwm got installed without any errors :+1:

**Comment by jl2** [comment]
I reverted the Makefile changes in this PR and [opened a new one ](https://github.com/stumpwm/stumpwm/pull/1018) that adds "--non-interactive" and sets SBCL's default encoding to UTF-8.

**Comment by PuercoPop** [comment]
Thanks for taking the time to tackle this :pray: :tada:

**Comment by cnoceda** [comment]
Thank you very much!!!!

**Comment by tiberious726** [comment]
With this PR merged, some time after starting stumpwm, I get an error from the sbcl-specialized ioloop method:

```
debugger invoked on a TYPE-ERROR @52AE264D in thread
#<THREAD "main thread" RUNNING {10025E0293}>:
  The value
    NIL
  is not of type
    NUMBER
```

I'll post more details if I uncover them

**Comment by shassard** [comment]
I'm experiencing the same crash over here, but hadn't had a chance to bisect it against this specific commit.

Here's the backtrace via `(copy-unhandled-error)`:

```
The value
  NIL
is not of type
  NUMBER
Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1005698073}>
0: ((:METHOD IO-LOOP (STUMPWM::SBCL-IO-LOOP)) #<STUMPWM::SBCL-IO-LOOP {1003E95033}> :DESCRIPTION "StumpWM") [fast-method]
1: (STUMPWM::STUMPWM-INTERNAL-LOOP)
2: (STUMPWM::STUMPWM-INTERNAL ":0")
3: (STUMPWM ":0")
4: (COMMON-LISP-USER::MAIN)
5: (ROSWELL::ENTRY "COMMON-LISP-USER::MAIN")
6: (ROSWELL:RUN ((:ENTRY "COMMON-LISP-USER::MAIN")))
7: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
8: ((FLET "WITHOUT-INTERRUPTS-BODY-3" :IN SB-IMPL::START-LISP))
9: (SB-IMPL::%START-LISP)
```

**Comment by tiberious726** [comment]
I've been running on f70c93ba (in addition to my pull-requests, and 6761f1f1 ) for a few hours now, no crashes, I could reliably get anything running on top of 9f476737 to crash in a few minuets.

**Comment by tiberious726** [comment]
#1020

**Pull request merged**
