### PR TITLE
Catch TYPE-ERROR when decoding window names.

### PR DESCRIPTION
**Pull request by shamazmazum**
Look at explanation [here](https://github.com/stumpwm/stumpwm/issues/641). To put it short: uxterm on FreeBSD puts UTF-8 encoded string in property WM_NAME of type STRING. This causes StumpWM to crash while decoding this string.

### CODE REVIEW

**Comment by PuercoPop** [comment]
@shamazmazum Sorry about the brain fart, indeed we need to handle the case when clients mistakenly put utf-8 strings w/o setting the appropriate property type.

Instead of making the handler case cover more forms could you please define a function named safely-decode-string that wraps the only the first branch of the if in and handles the type error?

**Comment by shamazmazum** [comment]
@PuercoPop Is it ok now? I've moved handler cases into two separate functions (I think, the other wants its own function too ;))

**Comment by shamazmazum** [comment]
Also, is StumpWM supported on other common lisp implementations or only on SBCL? Is it correct to use SBCL-specific functions? Flexi-streams should provide platform-independent octets-to-string

**Comment by PuercoPop** [comment]
> (I think, the other wants its own function too ;)

I think just calling `utf8-to-string` would be better. Less code, less problems (Sorry im asking you to remove code I just wrote :shame:

> Is StumpWM supported [...] only on SBCL?

Yes

> Is it correct to use SBCL-specific functions? 

Yes

**Comment by shamazmazum** [comment]
I am sorry. Pushed wrong code. This is obviously an error:

>(if (eq encoding :x11-string)
          (safely-decode-x11-string name)
          (sb-ext:octets-to-string string :external-format encoding)))

Already fixed it in my branch but it was too late

**Comment by shamazmazum** [comment]
@PuercoPop Can you please fix it? Or I need to open another pull request? The line

> (sb-ext:octets-to-string string :external-format encoding)

needs to be replaced with

> (utf8-to-string name)

**Pull request merged**
