### PR TITLE
Export symbol only-one-frame-p

### PR DESCRIPTION
**Pull request by tobyWorland**

### CODE REVIEW

**Comment by dmb2** [comment]
Please explain why this is needed.  If you are developing a module and require the symbol explain the context.

**Comment by tobyWorland** [comment]
Apologies.
I wanted to add an option to the gaps contrib that would only add gaps if there is more than one frame. I planned to use this symbol to do so.

**Comment by dmb2** [comment]
Please add it to the manual and I'll merge this.

**Comment by tobyWorland** [comment]
It seems someone had already added it to the manual prior to me exporting it.
https://github.com/tobyWorland/stumpwm/blob/db34981389c412a493ccc9fbdce0e81369d57c7b/stumpwm.texi.in#L1878

**Pull request merged**
