### PR TITLE
Add KILL-WINDOWS command

### PR DESCRIPTION
**Pull request by selesdepselesnul**
Kill all windows in the current group

### CODE REVIEW

**Comment by dbjergaard** [comment]
Hi,

Please refactor into a defun by removing `current-group` and replace it with a group argument.  This keeps things a bit more general and lets you kill windows in another group.  

If you want to keep the current behavior, add another defcommand calling the refactored function.  Can we name it something a little more clear? `kill-windows-current-group` is a bit verbose, but does explain exactly what it does.

**Comment by selesdepselesnul** [comment]
done :smile:

**Comment by dbjergaard** [comment]
I like your proposal better.  I'm happy to merge as is... Let me know.

**Comment by selesdepselesnul** [comment]
done :smile:

**Comment by dbjergaard** [comment]
Beautiful!

**Pull request merged**
