### PR TITLE
Add: `remove-all-hooks`

### PR DESCRIPTION
**Pull request by AeroNotix**
Removes all functions from a hook.

### CODE REVIEW

**Comment by dbjergaard** [comment]
Why can't a user just write (setf hook-name nil)?

**Comment by AeroNotix** [comment]
They can, but then why can't a user just write `(setf hook (remove fn hook))`?

**Comment by dbjergaard** [comment]
I really appreciate the code contribution, but to me this adds a level of indirection that isn't needed.  (remove-hook fn hook) is a well defined operation.  It expands to a relatively simple piece of code, but it doesn't require mental gynmastics to operate it.  On the other hand:
(setf hook (remove fn hook))
does.  Clearing a hook by setting it nil is one step (setf hook nil) and is easily mentally parsed.  

Can we compromise and update the manual to explain how to remove hooks using setf?

**Comment by PuercoPop** [comment]
@dbjergaard I think @AeroNotix was being cryptic by asking a rhetorical question. Their point is, we provide APIs to abstract over implementation details. What happens if we change how we store hooks from a list to a custom set implementation (fset or otherwise)? Users would have to rewrite calls to `(setf hook-name nil)`.

We provide some abstractions in that spirit such as `add-screen-mode-line-formatter`. But then again most of the code in StumpWM-contribs didn't used it and instead pushed to `*screen-mode-line-formatter*` instead.

**Comment by dbjergaard** [comment]
@PuercoPop makes a good point.  I'm all for abstraction, but I don't want it at the expense of increasing maintenance overhead. @AeroNotix if you want to re-open this PR, I'll merge it.

**Comment by dbjergaard** [comment]
@AeroNotix I look forward to more PRs :+1:

**Comment by AeroNotix** [comment]
:+1:

**Pull request merged**
