### PR TITLE
Window placement improvements

### PR DESCRIPTION
**Pull request by mtlll**
#434

### CODE REVIEW

**Comment by mtlll** [comment]
Could use some feedback on the last commit. Would it perhaps be better to do something along the lines of:
```lisp
(frame-raise-window group to-frame win raise-p)
```

instead of omitting the entire call?

**Comment by dbjergaard** [comment]
I will try to look at this tonight. 

    David

**Comment by dbjergaard** [comment]
I think that we should always raise the window when pulling. That’s why the original code ignore the raise request and unconditionally raised the window.

**Comment by mtlll** [comment]
So then it would perhaps be better to conditionally focus the window instead? I think that would be more reasonable. I'll update the PR soon.

**Pull request merged**
