### PR TITLE
More documentation fixes 2

### PR DESCRIPTION
**Pull request by impaktor**
Some more typo fixes. (Note to self: I'm now on page 33 of 70 on pdf-version of manual).

### CODE REVIEW

**Comment by PuercoPop** [comment]
@dbjergaard @jorams How do y'all feel about ba87203d7d82ced07a3639143813ed30b5520136?
I prefer using uppercase for all symbols that refer to functions/variables/etc, but I'm aware it is an archaism at this point.

@impaktor @ecraven Thanks for proof-reading the manual!

**Comment by impaktor** [comment]
I have  no opinion one way or another, but my impression is that lowercase is by far the most frequent in the manual, thus I opted for the path of least resistance.

In general, I don't think there is a standard in the manual for how to typeset key words, functions, and variable names?

**Comment by PuercoPop** [comment]
@impaktor Don't worry, I would have chosen the same approach as you in your place.

The [convention is more a common lispone](https://google.github.io/styleguide/lispguide.xml?showone=Document_everything#Document_everything), but is becoming increasingly uncommon. And we embed texinfo in our docstrings so we are already unconventional.

**Comment by impaktor** [comment]
I've found some more typos, some fitted nicely in the other commits, so squashed those changes into there (like capitalize new sentences), and I also removed the controversial "is it `NIL` or `nil`" as further in, e.g. chapter 12, most variables are uppercase, so I myself can't be consistent, thus I removed it.

**Comment by PuercoPop** [comment]
@impaktor Thanks 🎉

**Pull request merged**
