### PR TITLE
Remove unnecessary progn

### PR DESCRIPTION
**Pull request by selesdepselesnul**

### CODE REVIEW

**Comment by PuercoPop** [comment]
Could we keep the newline between `with-restarts-menu` and `handler-case`(

**Comment by selesdepselesnul** [comment]
Done :smile:

**Comment by PuercoPop** [comment]
@selesdepselesnul Sorry, I forgot to mention, with the appropriate indentation (what emacs + S{ly,ime} does). :pray: 

```lisp
(defcommand loadrc () ()
"Reload the @file{~/.stumpwmrc} file."
  (handler-case
      (with-restarts-menu (load-rc-file nil))
    (error (c)
      (message "^1*^BError loading rc file: ^n~A" c))
    (:no-error (&rest args)
      (declare (ignore args))
      (message "rc file loaded successfully."))))
```

**Comment by selesdepselesnul** [comment]
done :smile:

**Comment by PuercoPop** [comment]
@selesdepselesnul Thanks!

**Pull request merged**
